### ISSUE TITLE
Inventory Setups disappeared from sidebar.

### ISSUE THREAD

**Issue by jpjfire** [dillydill123/inventory-setups#122]
The icon for inventory setups has disappeared from my Runelite sidebar.  It still shows in the external plugins lists, and gives me the option to remove it, so it is installed. There is no on/off switch to turn it on. Any help in getting it back, hopefully with all my settings intact, would really be appreciated. Thanks.

**Comment by jakerobers** [comment]
I'm seeing the same on my end too. I'm guessing it has to do with the most recent update.

The stacktrace that I'm seeing is:
```
net.runelite.client.util.VerificationException: Plugin bot-detector didn't match its hash
        at net.runelite.client.externalplugins.ExternalPluginManager.refreshPlugins(ExternalPluginManager.java:238)
        at net.runelite.client.externalplugins.ExternalPluginManager.loadExternalPlugins(ExternalPluginManager.java:115)
        at net.runelite.client.RuneLite.start(RuneLite.java:296)
        at net.runelite.client.RuneLite.main(RuneLite.java:251)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:63)
```

Your inventory setups should be fine. If you check the `settings.properties` file in your runelite folder, you can search for `inventorysetups`.

**Comment by jpjfire** [comment]
It's back! Thanks!

**Comment by dillydill123** [comment]
Yep this broke as part the recent update. The mechanism for detecting the plugin version uses the `Properties` module which has a header that includes the timestamp in the plugin jar. This was causing some issue according to the RuneLite devs. So I've updated the plugin to use a simple txt file instead to store the plugin version instead.

Generally on an update day if any plugin is missing, it's likely due to OSRS/RL update. Your data will never be deleted even if the plugin is gone. It will still be in your configurations (which are saved on the cloud if you log into RL). That being said, I do recommend taking advantage of the "Mass Export" option Inventory Setups has if you want another way to save your setups. As mentioned above, if you log into RuneLite, your settings are stored on the cloud. This includes your setups from this plugin.

**Comment by jpjfire** [comment]
Thanks for the info, and for getting it fixed almost immediately.
