### ISSUE TITLE
Inventory setups do not filter bank, on runelite version 1.10.38

### ISSUE THREAD

**Issue by geheur** [dillydill123/inventory-setups#269]
if it is selected before the bank is opened it works.

**Comment by geheur** [comment]
```
java.lang.AssertionError: must be called on client thread
	at client.getItemContainer(client.java:48726)
	at inventorysetups.InventorySetupsPlugin.getNormalizedContainer(InventorySetupsPlugin.java:1917)
	at inventorysetups.ui.InventorySetupsPluginPanel.doHighlighting(InventorySetupsPluginPanel.java:774)
	at inventorysetups.ui.InventorySetupsPluginPanel.setCurrentInventorySetup(InventorySetupsPluginPanel.java:746)
	at inventorysetups.ui.InventorySetupsStandardPanel$6.mousePressed(InventorySetupsStandardPanel.java:358)
```

**Comment by dillydill123** [comment]
I think you fixed this right?
