### ISSUE TITLE
Plugin doesnt work with the latest version of Runelite

### ISSUE THREAD

**Issue by mathiasHillmann** [dillydill123/inventory-setups#307]
[Runelite's commit](https://github.com/runelite/runelite/commit/cebc6995552c3db0adf83649b1331fc5b5c438d5)
[Log](https://repo.runelite.net/plugins/log/inventory-setups/1.10.44_c6062e73131d329d24fe84218e1a9b7a887404e4.log)

Build log:
```
API changed; rebuild needed. changed:
Lnet/runelite/client/plugins/banktags/BankTagsService;.OPTION_HIDE_REMOVE_TAG_NAME:I:bsf:2
apicheck: 39ms
Cloning into '/tmp/pluginhub-package14041540798577336294/inventory-setups/repo'...
HEAD is now at c6062e7 Remove period for consistency
download: 3265ms
File "readme_images_and_gifs/update_slot_from_search.gif" is skipped from the source archive as it would make it too big (1 MiB)
File "readme_images_and_gifs/bank_filtering.gif" is skipped from the source archive as it would make it too big (1 MiB)
File "readme_images_and_gifs/update_icon.gif" is skipped from the source archive as it would make it too big (1 MiB)
File "readme_images_and_gifs/auto_layout.gif" is skipped from the source archive as it would make it too big (1 MiB)

> Task :compileJava
/tmp/pluginhub-package14041540798577336294/inventory-setups/repo/src/main/java/inventorysetups/InventorySetupsPlugin.java:169: error: cannot find symbol
	private static final int BANK_TAG_OPTIONS = BankTagsService.OPTION_ALLOW_MODIFICATIONS | BankTagsService.OPTION_HIDE_REMOVE_TAG_NAME;
	                                                                                                        ^
  symbol:   variable OPTION_HIDE_REMOVE_TAG_NAME
  location: interface BankTagsService
/tmp/pluginhub-package14041540798577336294/inventory-setups/repo/src/main/java/inventorysetups/InventorySetupsPlugin.java:774: error: cannot find symbol
			bankTagsService.openBankTag(new_.getTag(), BankTagsService.OPTION_HIDE_REMOVE_TAG_NAME);
			                                                          ^
  symbol:   variable OPTION_HIDE_REMOVE_TAG_NAME
  location: interface BankTagsService
2 errors

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 15s
1 actionable task: 1 executed
build: 16933ms
package failed
net.runelite.pluginhub.packager.PluginBuildException: inventory-setups: build failed
	at net.runelite.pluginhub.packager.PluginBuildException.of(PluginBuildException.java:54)
	at net.runelite.pluginhub.packager.Plugin.build(Plugin.java:543)
	at net.runelite.pluginhub.packager.Packager.buildPlugin(Packager.java:215)
	at net.runelite.pluginhub.packager.Packager.lambda$buildPlugins$0(Packager.java:155)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.gradle.tooling.BuildException: Could not execute build using connection to Gradle installation '/home/runner/.gradle/wrapper/dists/gradle-8.10-all/3ym48ijgw9iixtry4iwty4ydy/gradle-8.10'.
	...
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
Caused by: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':compileJava'.
	...
Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
	...
	... 2 more
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	...
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	...
	... 28 more


inventory-setups: build failed


```

Seems like Runelite has change the name for the constant `OPTION_HIDE_REMOVE_TAG_NAME` to `OPTION_HIDE_TAG_NAME `

**Comment by dillydill123** [comment]
Should be fixed now. There is a new update coming using some of the new changes from runelite core
