### ISSUE TITLE
Crash on Bank Open

### ISSUE THREAD

**Issue by LlemonDuck** [dillydill123/inventory-setups#99]
While running the plugin I had the following error while opening my bank very quickly after logging in and using the search button. It induced a game crash and required a client restart.

```
2021-07-03 02:39:29 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.AssertionError: Script 299 was called with the incorrect number of arguments; takes 3+0, got 2+0
	at client.fz(client.java:33504)
	at client.runScript(client.java:19350)
	at inventorysetups.InventorySetupsBankSearch.lambda$reset$0(InventorySetupsBankSearch.java:82)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:61)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:46)
	at inventorysetups.InventorySetupsBankSearch.reset(InventorySetupsBankSearch.java:75)
	at inventorysetups.InventorySetupsPlugin.resetBankSearch(InventorySetupsPlugin.java:753)
	at inventorysetups.InventorySetupsPlugin.onScriptPreFired(InventorySetupsPlugin.java:875)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:66)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:219)
	at net.runelite.client.callback.Hooks.post(Hooks.java:169)
```

Unfortunately I don't have much more information at the moment :(

Edit: Now has happened twice, same error.

RuneLite build 1.7.15-SNAPSHOT, revision 14571bd15f11602a0d6386c01540ab33470f98fe. May not be present in current release (1.7.14.2 as of writing), since I didn't encounter it there.

**Comment by dillydill123** [comment]
I think your plugin was out of date, because I fixed this in https://github.com/dillydill123/inventory-setups/issues/96. The stack looks like the previous version which had the bug. https://github.com/dillydill123/inventory-setups/blob/master/src/main/java/inventorysetups/InventorySetupsBankSearch.java

**Comment by LlemonDuck** [comment]
Cool, thanks for the response. :)

Maybe I had my plugin hub version overridden to some old value, I'll check it.
